### ISSUE TITLE
请问可以增加些多类别变化检测的代码吗，而不是现在这种只能检测两类

### ISSUE THREAD

**Issue by swjtulinxi** [likyoo/change_detection.pytorch#11]

**Comment by likyoo** [comment]
你好，请问您说的多类别变化检测具体是什么任务呢？只修改`classes`参数会有问题吗？

**Comment by swjtulinxi** [comment]
我们现在的变化检测都是做两类，比如建筑物变化检测，我的意思是多类别，比如从现在的类别过渡到下一个什么类别，比如建筑物、公路、草地等一次性检测出多个类别的变化

**Comment by likyoo** [comment]
您好，目前来说还不支持。我们会考虑在未来支持多类别变化检测方法。
如果方便的话，您可以在这个[issue](https://github.com/likyoo/change_detection.pytorch/issues/10#issue-1080643504)中写一下具体的需求。如：
```
支持多类别变化检测 
参考方法/数据：https://github.com/LiheYoung/SenseEarth2020-ChangeDetection
```

您也可以修改代码后推送请求 :)
