### ISSUE TITLE
How to obtain the forecast image

### ISSUE THREAD

**Issue by chenhaiwen** [likyoo/change_detection.pytorch#2]
There is no code for batch generation of predictive images using trained models, thank you

**Comment by isshf** [comment]
I want to obtain the forecast image, Can you tell me how to obtain it ? Thank you

**Comment by likyoo** [comment]
@chenhaiwen Sorry, batch inference&saving is not supprt now.

**Comment by likyoo** [comment]
@isshf You can refer this :
```
valid_epoch.infer_vis(valid_loader, slide=True, image_size=1024, window_size=256,
                      save_dir='./res')
```
Please note that this function is weakly robust and only supports batch_size=1 now.
