### ISSUE TITLE
Suggest to loosen the dependency on albumentations

### ISSUE THREAD

**Issue by Agnes-U** [likyoo/change_detection.pytorch#24]
Hi, your project change_detection.pytorch(commit id: 0a86d51b31276d9c413798ab3fb332889f02d8aa) requires "albumentations==1.0.3" in its dependency. After analyzing the source code, we found that the following versions of albumentations can also be suitable, i.e., albumentations 1.0.0, 1.0.1, 1.0.2, since all functions that you directly (8 APIs: albumentations.core.transforms_interface.BasicTransform.__init__, albumentations.augmentations.geometric.resize.Resize.__init__, albumentations.core.composition.Compose.__init__, albumentations.pytorch.transforms.ToTensorV2.__init__, albumentations.augmentations.crops.functional.random_crop, albumentations.core.transforms_interface.DualTransform.__init__, albumentations.augmentations.crops.transforms.RandomCrop.__init__, albumentations.augmentations.transforms.Normalize.__init__) or indirectly (propagate to 11 albumentations's internal APIs and 0 outsider APIs) used from the package have not been changed in these versions, thus not affecting your usage.

Therefore, we believe that it is quite safe to loose your dependency on albumentations from "albumentations==1.0.3" to "albumentations>=1.0.0,<=1.0.3". This will improve the applicability of change_detection.pytorch and reduce the possibility of any further dependency conflict with other projects. 

May I pull a request to further loosen the dependency on albumentations?

By the way, could you please tell us whether such an automatic tool for dependency analysis may be potentially helpful for maintaining dependencies easier during your development?

**Comment by likyoo** [comment]
Many thanks for your kind reminder, please create a pr to fix it 😄

**Comment by likyoo** [comment]
And In fact, we did not do some automatic dependency analysis. 😞

**Comment by Agnes-U** [comment]
Thank you for your reply! I found that this modification has been merged before, [here](https://github.com/likyoo/change_detection.pytorch/commit/2d40f83c598d5c2f73900eeca6791180b9e1d1e6), thanks~
