### ISSUE TITLE
BCL

### ISSUE THREAD

**Issue by ghasem-abdi** [likyoo/change_detection.pytorch#5]
There is a bcl.py in losses but it is not compatible with the package and I received error. Could you please advise?

**Comment by LinoSun** [comment]
> There is a bcl.py in losses but it is not compatible with the package and I received error. Could you please advise?

Could you please show more detals about the error you received?

**Comment by ghasem-abdi** [comment]
In the local_test.py, I changed the loss ("loss = cdp.utils.losses.CrossEntropyLoss()") with "loss = cdp.losses.bcl.BCLLoss()" but I received this error:
"RuntimeError: The size of tensor a (2) must match the size of tensor b (8) at non-singleton dimension 1"

**Comment by LinoSun** [comment]
> In the local_test.py, I changed the loss ("loss = cdp.utils.losses.CrossEntropyLoss()") with "loss = cdp.losses.bcl.BCLLoss()" but I received this error: "RuntimeError: The size of tensor a (2) must match the size of tensor b (8) at non-singleton dimension 1"

BCLLoss function received pred.shape is (Batch,1,Height,Weight), which pred is distance map. Reference:https://www.researchgate.net/publication/341586750_A_Spatial-Temporal_Attention-Based_Method_and_a_New_Dataset_for_Remote_Sensing_Image_Change_Detection

**Comment by likyoo** [comment]
Hi, @ghasem-abdi 
"2" means the 'classes=2' in your model configuration, [here](https://github.com/likyoo/change_detection.pytorch/blob/0be35105b2b89ef1b3be51dbdc0d88177adb83a3/local_test.py#L14).
If you want to use BCE loss, you can set ‘classes=1’, or convert your label to a one-hot form.

There may be other errors when using Epoch.run directly (this is just a sample function, not robust enough). The squeeze() function and some data type conversions may be helpful to you.

By the way, the activation function in your ‘metrics’ may need to be changed from "argmax2d" to "sigmoid".
