### ISSUE TITLE
Question about the pretrained model

### ISSUE THREAD

**Issue by l912237463** [likyoo/change_detection.pytorch#8]
Since the number of data channels is not 3, I cannot use the pre-trained model. How can I modify the code

**Comment by likyoo** [comment]
You just need to change `in_channels` in your model.
For using pretrained model, refer [here](https://github.com/likyoo/change_detection.pytorch/blob/7221a9304a1202c52fd8b798780614af28aa38d8/change_detection_pytorch/encoders/_utils.py#L5).
