### ISSUE TITLE
unsupported operand type(s) for /: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by mst272** [likyoo/change_detection.pytorch#9]
unsupported operand type(s) for /: 'NoneType' and 'int'。  
![image](https://user-images.githubusercontent.com/67250532/145714500-f0c22aa1-c7bc-4fa6-8d59-c2826342cb4b.png)
![image](https://user-images.githubusercontent.com/67250532/145714506-ce626e36-970c-44fc-bd8b-81c3d34cc750.png)

That's why?

**Comment by likyoo** [comment]
你好，这很有可能是没有读到有效数据导致的。
请检查一下数据路径和图像后缀名是否正确。
